In [85]:
# *********************************************
#         Task1 - Data Cleaning
# *********************************************

In [86]:
# loading data
import pandas as pd
df = pd.read_csv(r"E:\Task1\Dataset\netflixData_raw_data.csv")

In [87]:
df.shape

(5967, 13)

In [88]:
df.head()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,NaN,Reality TV,NaN,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,"September 8, 2020"
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,"July 1, 2020"
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,NaN,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",NaN,Canada,2020.0,TV-14,90 min,5.1/10,Movie,"February 5, 2020"

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5967 entries, 0 to 5966
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Show Id             5967 non-null   object
 1   Title               5967 non-null   object
 2   Description         5967 non-null   object
 3   Director            3903 non-null   object
 4   Genres              5967 non-null   object
 5   Cast                5437 non-null   object
 6   Production Country  5408 non-null   object
 7   Release Date        5964 non-null   float64
 8   Rating              5963 non-null   object
 9   Duration            5964 non-null   object
 10  Imdb Score          5359 non-null   object
 11  Content Type        5967 non-null   object
 12  Date Added          4632 non-null   object
dtypes: float64(1), object(12)
memory usage: 606.2+ KB

In [90]:
# removing duplicates
dup = df.duplicated().sum()
print(dup)

0

In [91]:
df = df.drop_duplicates()

In [92]:
df.shape

(5967, 13)

In [93]:
# Null handling
df.isnull().sum()

Show Id                  0
Title                    0
Description              0
Director              2064
Genres                   0
Cast                   530
Production Country     559
Release Date             3
Rating                   4
Duration                 3
Imdb Score             608
Content Type             0
Date Added            1335
dtype: int64

In [94]:
df["Director"] = df["Director"].fillna("Unknown")

In [95]:
df["Director"].isna().sum()

np.int64(0)

In [96]:
df["Cast"] = df["Cast"].fillna("Not Mentioned")

In [97]:
df["Cast"].isnull().sum()

np.int64(0)

In [98]:
df["Production Country"] = df["Production Country"].fillna("Unknown")

In [99]:
df["Production Country"].isnull().sum()

np.int64(0)

In [100]:
df = df.dropna(subset="Release Date")

In [101]:
df["Release Date"].isna().sum()

np.int64(0)

In [102]:
df["Rating"] = df["Rating"].fillna("No Rating")

In [103]:
df["Release Date"].isna().sum()

np.int64(0)

In [104]:
df = df.dropna(subset="Duration")

In [105]:
df["Duration"].isna().sum()

np.int64(0)

In [106]:
df["Imdb Score"] = df["Imdb Score"].fillna("Not Available")

In [107]:
df["Imdb Score"].isna().sum()

np.int64(0)

In [108]:
df[df["Date Added"].isna()]

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,Unknown,Reality TV,Not Mentioned,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,Unknown,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
13,91c48de3-5bc6-43e8-ae4c-944a0b190687,100 Days My Prince,"Upon losing his memory, a crown prince encount...",Unknown,"International TV Shows, Romantic TV Shows, TV ...","Doh Kyung-soo, Nam Ji-hyun, Cho Seong-ha, Cho ...",South Korea,2018.0,TV-14,1 Season,7.5/10,TV Show,NaN
14,3ad83357-9327-48bb-b89d-862d61b5801e,100 Humans,One hundred hardy souls from diverse backgroun...,Unknown,"Docuseries, Science & Nature TV","Zainab Johnson, Sammy Obeid, Alie Ward",United States,2020.0,TV-14,1 Season,5.5/10,TV Show,NaN
28,dbb44ca4-c401-472a-8265-54514b04cb7c,1983,"In this dark alt-history thriller, a naïve law...",Unknown,"Crime TV Shows, International TV Shows, TV Dramas","Robert Więckiewicz, Maciej Musiał, Michalina O...","Poland, United States",2018.0,TV-MA,1 Season,7.0/10,TV Show,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5945,d143fc8e-0470-4dc8-a65f-5dc59370d776,Zindagi in Short,"Complicated marriages, digital romances, domes...",Unknown,"International TV Shows, TV Dramas",Not Mentioned,India,2020.0,TV-MA,1 Season,7.3/10,TV Show,NaN
5951,3eee1663-92d7-4b63-943d-bbfd66635295,Zoids Wild,A quest for freedom and legendary treasure beg...,Unknown,"Anime Series, Kids' TV","Kensho Ono, Takahiro Sakurai, Mikako Komatsu, ...",Japan,2018.0,TV-Y7,1 Season,Not Available,TV Show,NaN
5954,e4d88cc9-8ee2-46b9-aac6-af786e6efbdb,Zona Rosa,An assortment of talent takes the stage for a ...,Unknown,"International TV Shows, Spanish-Language TV Sh...","Manu NNa, Ana Julia Yeyé, Ray Contreras, Pablo...",Mexico,2019.0,TV-MA,1 Season,5.7/10,TV Show,NaN
5963,5bed77ab-5e31-4216-8b51-44c9a35442e6,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,Unknown,"International TV Shows, TV Dramas","Bashar al-Shatti, Fatima Al Safi, Maram Baloch...",Unknown,2019.0,TV-14,1 Season,Not Available,TV Show,NaN
5964,4661ec0c-8692-4661-bc76-a96412b311fd,海的儿子,"Two brothers start a new life in Singapore, wh...",Unknown,"International TV Shows, TV Dramas","Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",Unknown,2016.0,TV-14,1 Season,Not Available,TV Show,NaN

In [109]:

df["Date Added"].dtype

dtype('O')

In [110]:
df["Date Added"] = df["Date Added"].bfill()

In [111]:
df["Date Added"].isna().sum()

np.int64(0)

In [112]:
df.isnull().sum()

Show Id               0
Title                 0
Description           0
Director              0
Genres                0
Cast                  0
Production Country    0
Release Date          0
Rating                0
Duration              0
Imdb Score            0
Content Type          0
Date Added            0
dtype: int64

In [113]:
# Changing Datatypes

In [114]:
df.dtypes

Show Id                object
Title                  object
Description            object
Director               object
Genres                 object
Cast                   object
Production Country     object
Release Date          float64
Rating                 object
Duration               object
Imdb Score             object
Content Type           object
Date Added             object
dtype: object

In [115]:
df["Title"] = df["Title"].astype("string")

In [116]:
columns = ["Description","Director" , "Genres", "Cast", "Production Country", "Content Type"]

In [117]:
df[columns] = df[columns].astype("string")

In [118]:
df["Date Added"] = pd.to_datetime(df["Date Added"])

In [119]:
df.dtypes

Show Id                       object
Title                 string[python]
Description           string[python]
Director              string[python]
Genres                string[python]
Cast                  string[python]
Production Country    string[python]
Release Date                 float64
Rating                        object
Duration                      object
Imdb Score                    object
Content Type          string[python]
Date Added            datetime64[ns]
dtype: object

In [120]:
df.head()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,Unknown,Reality TV,Not Mentioned,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,2020-09-08
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,2020-09-08
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,2020-07-01
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,Unknown,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,2020-02-05
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",Not Mentioned,Canada,2020.0,TV-14,90 min,5.1/10,Movie,2020-02-05

In [126]:
# Standardizing columns
df.colums = df.columns.str.replace("","_")

In [127]:
df.head()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,Unknown,Reality TV,Not Mentioned,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,2020-09-08
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,2020-09-08
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,2020-07-01
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,Unknown,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,2020-02-05
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",Not Mentioned,Canada,2020.0,TV-14,90 min,5.1/10,Movie,2020-02-05

In [129]:
df.to_csv(r"E:\Task1\Dataset\Netflix_cleaned_data.csv", index=False)